import type { SystemConfig } from '../interfaces/SystemConfig';

export const DEFAULT_SYSTEM_CONFIG: SystemConfig = {
  admin: {
    adminEmail: 'root@dracula.io',
    systemId: 'MT-CORE-X1',
    siteName: 'MultiTerm 多人博客系统',
    siteDescription: '一款专为极客设计的终端审美多人博客管理平台，深度集成 Dracula Soft 主题。',
    maintenanceMode: false,
    dashboardRefreshRate: 5000,
    showQuickDraft: true,
    enableAiAssistant: true,
    autoSaveInterval: 30,
    allowAuthorCustomCategories: true,
    statsApiEndpoint: '/api/v1/metrics',
    statsTool: 'INTERNAL',
    allowRegistration: true,
    defaultUserRole: 'author',
    recycleBinRetentionDays: 30,
    activeEffectMode: 'SNOW_FALL',
    font: {
      face: 'ComicShannsMono Nerd Font, Symbols Nerd Font, FangSong',
      weight: 'normal',
    },
  },
  frontend: {
    site: 'https://blog.karenepitaya.xyz',
    title: "Karene's Blog",
    description: 'A multi-author blog powered by our server public API',
    author: 'Karene Pitayas',
    tags: ['Astro', 'MultiTerm', 'Blog', 'karenepitaya'],
    faviconUrl: '/favicon.svg',
    socialCardAvatarImage: './public/social-avatar.jpg',
    font: 'JetBrains Mono Variable',
    pageSize: 6,
    trailingSlashes: false,
    navLinks: [
      { name: 'Home', url: '/' },
      { name: 'About', url: '/about' },
      { name: 'Archive', url: '/posts' },
      { name: 'GitHub', url: 'https://github.com/karenepitaya', external: true },
    ],
    themes: {
      mode: 'select',
      default: 'catppuccin-mocha',
      include: [
        'andromeeda',
        'aurora-x',
        'ayu-dark',
        'catppuccin-frappe',
        'catppuccin-latte',
        'catppuccin-macchiato',
        'catppuccin-mocha',
        'dark-plus',
        'dracula',
        'dracula-soft',
        'everforest-dark',
        'everforest-light',
        'github-dark',
        'github-dark-default',
        'github-dark-dimmed',
        'github-dark-high-contrast',
        'github-light',
        'github-light-default',
        'github-light-high-contrast',
        'gruvbox-dark-hard',
        'gruvbox-dark-medium',
        'gruvbox-dark-soft',
        'gruvbox-light-hard',
        'gruvbox-light-medium',
        'gruvbox-light-soft',
        'houston',
        'kanagawa-dragon',
        'kanagawa-lotus',
        'kanagawa-wave',
        'laserwave',
        'light-plus',
        'material-theme',
        'material-theme-darker',
        'material-theme-lighter',
        'material-theme-ocean',
        'material-theme-palenight',
        'min-dark',
        'min-light',
        'monokai',
        'night-owl',
        'nord',
        'one-dark-pro',
        'one-light',
        'plastic',
        'poimandres',
        'red',
        'rose-pine',
        'rose-pine-moon',
        'rose-pine-dawn',
        'slack-dark',
        'slack-ochin',
        'snazzy-light',
        'solarized-dark',
        'solarized-light',
        'synthwave-84',
        'tokyo-night',
        'vesper',
        'vitesse-black',
        'vitesse-dark',
        'vitesse-light',
      ],
      overrides: {},
    },
    socialLinks: {
      github: 'https://github.com/karenepitaya',
      mastodon: 'https://github.com/karenepitaya',
      email: 'https://github.com/karenepitaya',
      linkedin: 'https://github.com/karenepitaya',
      bluesky: 'https://github.com/karenepitaya',
      twitter: 'https://github.com/karenepitaya',
    },
    characters: {
      owl: '/owl.webp',
      unicorn: '/unicorn.webp',
      duck: '/duck.webp',
    },
  },
  oss: {
    enabled: false,
    provider: 'oss',
    endpoint: '',
    bucket: '',
    accessKey: '',
    secretKey: '',
    region: '',
    customDomain: '',
    uploadPath: '',
    imageCompressionQuality: 0.8,
  },
};
