
import React from 'react';
import type { IconType } from 'react-icons';
import {
  FiBarChart2,
  FiCheck,
  FiEdit2,
  FiFileText,
  FiGrid,
  FiLayers,
  FiLogOut,
  FiPlus,
  FiRefreshCcw,
  FiSettings,
  FiTag,
  FiTerminal,
  FiTrash2,
  FiUpload,
  FiUsers,
  FiZap,
} from 'react-icons/fi';
import { SystemConfig, UserRole, VisualEffectMode } from './types';

export const DEFAULT_AI_SYSTEM_PROMPT = [
  '你是专业的博客编辑助手。',
  '请根据用户提供的 Markdown 内容输出严格 JSON。',
  '{ "title": string, "summary": string, "tags": string[], "suggestedSlug": string, "readingTimeMinutes": number }',
  'summary 不超过 200 字，tags 建议 3-6 个中文关键词。',
  '只输出 JSON，不要 Markdown 包裹。',
].join('\n');

export const INITIAL_CONFIG: SystemConfig = {
  admin: {
    adminEmail: 'root@dracula.io',
    systemId: 'MT-CORE-X1',
    siteName: 'MultiTerm 多人博客系统',
    siteDescription: '一款专为极客设计的终端审美多人博客管理平台，深度集成 Dracula Soft 主题。',
    maintenanceMode: false,
    dashboardRefreshRate: 5000,
    showQuickDraft: true,
    enableAiAssistant: true,
    autoSaveInterval: 120,
    allowAuthorCustomCategories: true,
    statsApiEndpoint: '/api/v1/metrics',
    statsTool: 'INTERNAL',
    allowRegistration: true,
    defaultUserRole: UserRole.AUTHOR,
    recycleBinRetentionDays: 30,
    activeEffectMode: VisualEffectMode.SNOW_FALL,
    font: {
      face: '"JetBrains Mono Variable", "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      weight: 'normal',
    },
  },
  frontend: {
    site: 'https://blog.karenepitaya.xyz',
    title: "Karene's Blog",
    description: 'A multi-author blog powered by our server public API',
    author: 'Karene Pitayas',
    tags: ['Astro', 'MultiTerm', 'Blog', 'karenepitaya'],
    faviconUrl: '/favicon.svg',
    socialCardAvatarImage: './public/social-avatar.jpg',
    font: 'JetBrains Mono Variable',
    pageSize: 6,
    trailingSlashes: false,
    navLinks: [
      {
        name: 'Home',
        url: '/',
      },
      {
        name: 'About',
        url: '/about',
      },
      {
        name: 'Archive',
        url: '/posts',
      },
      {
        name: 'GitHub',
        url: 'https://github.com/karenepitaya',
        external: true,
      },
    ],
    themes: {
      mode: 'select',
      default: 'catppuccin-mocha',
      include: [
        'andromeeda',
        'aurora-x',
        'ayu-dark',
        'catppuccin-frappe',
        'catppuccin-latte',
        'catppuccin-macchiato',
        'catppuccin-mocha',
        'dark-plus',
        'dracula',
        'dracula-soft',
        'everforest-dark',
        'everforest-light',
        'github-dark',
        'github-dark-default',
        'github-dark-dimmed',
        'github-dark-high-contrast',
        'github-light',
        'github-light-default',
        'github-light-high-contrast',
        'gruvbox-dark-hard',
        'gruvbox-dark-medium',
        'gruvbox-dark-soft',
        'gruvbox-light-hard',
        'gruvbox-light-medium',
        'gruvbox-light-soft',
        'houston',
        'kanagawa-dragon',
        'kanagawa-lotus',
        'kanagawa-wave',
        'laserwave',
        'light-plus',
        'material-theme',
        'material-theme-darker',
        'material-theme-lighter',
        'material-theme-ocean',
        'material-theme-palenight',
        'min-dark',
        'min-light',
        'monokai',
        'night-owl',
        'nord',
        'one-dark-pro',
        'one-light',
        'plastic',
        'poimandres',
        'red',
        'rose-pine',
        'rose-pine-moon',
        'rose-pine-dawn',
        'slack-dark',
        'slack-ochin',
        'snazzy-light',
        'solarized-dark',
        'solarized-light',
        'synthwave-84',
        'tokyo-night',
        'vesper',
        'vitesse-black',
        'vitesse-dark',
        'vitesse-light',
      ],
      overrides: {},
    },
    socialLinks: {
      github: 'https://github.com/karenepitaya',
      mastodon: 'https://github.com/karenepitaya',
      email: 'https://github.com/karenepitaya',
      linkedin: 'https://github.com/karenepitaya',
      bluesky: 'https://github.com/karenepitaya',
      twitter: 'https://github.com/karenepitaya',
    },
    giscus: undefined,
    characters: {
      owl: '/owl.webp',
      unicorn: '/unicorn.webp',
      duck: '/duck.webp',
    },
  },
  oss: {
    enabled: false,
    provider: 'oss',
    endpoint: '',
    bucket: '',
    accessKey: '',
    secretKey: '',
    region: '',
    customDomain: '',
    uploadPath: '',
    imageCompressionQuality: 0.8,
  },
};

export const UI_COLORS = {
  bg: '#0b0c15',
  card: '#21222c',
  border: '#44475a',
  accent: '#bd93f9',
  accentMuted: '#6272a4',
  text: '#f8f8f2',
  textMuted: '#6272a4',
  danger: '#ff5545',
  success: '#50fa7b',
  warning: '#f1fa8c',
  info: '#8be9fd',
};

type IconWrapperProps = {
  icon: IconType;
  className?: string;
};

const IconWrapper: React.FC<IconWrapperProps> = ({ icon: Icon, className }) => (
  <Icon className={`w-5 h-5 block shrink-0 ${className ?? ''}`} aria-hidden />
);

const makeIcon = (Icon: IconType) => () => <IconWrapper icon={Icon} />;

export const Icons = {
  Dashboard: makeIcon(FiGrid),
  Stats: makeIcon(FiBarChart2),
  Articles: makeIcon(FiFileText),
  Users: makeIcon(FiUsers),
  Categories: makeIcon(FiLayers),
  Tags: makeIcon(FiTag),
  Logs: makeIcon(FiTerminal),
  Recycle: makeIcon(FiTrash2),
  Settings: makeIcon(FiSettings),
  Logout: makeIcon(FiLogOut),
  Plus: makeIcon(FiPlus),
  Edit: makeIcon(FiEdit2),
  Check: makeIcon(FiCheck),
  Trash: makeIcon(FiTrash2),
  Restore: makeIcon(FiRefreshCcw),
  Upload: makeIcon(FiUpload),
  Sparkles: makeIcon(FiZap),
};

